import { useState, useEffect } from "react";
import type { ReactNode } from "react";
import {
  Link,
  Navigate,
  Outlet,
  Route,
  Routes,
  useLocation,
} from "react-router-dom";

import BallotQuestion from "./components/ballot-question";
import ContentSchemata from "./components/content-schemata";
import ConceptF from "./components/concept-f";
import ConceptG from "./components/concept-g";
import ConceptH from "./components/concept-h";
import BallotQuestions from "./components/ballot-questions";
import RentControlAlt from "./components/rent-control-alt";

// Sticky disclaimer shown on certain prototypes; content scrolls under it.
function DisclaimerBar({ children }: { children: ReactNode }) {
  return (
    <div className="sticky top-0 z-40 h-[37px] bg-[#fef3c7] border-b border-[#f59e0b] px-[16px] flex items-center gap-[8px]">
      <span className="text-[16px]">⚠️</span>
      <p className="font-['Nunito'] font-bold text-[13px] text-[#92400e] leading-[1.4]">
        {children}
      </p>
    </div>
  );
}

// Route sections, used to group prototypes in the dev nav.
const GROUPS = [
  { key: "ballot-questions", title: "MAPLE · Ballot Questions" },
  { key: "2024-audit", title: "2024 Ballot Question · Audit" },
] as const;

type GroupKey = (typeof GROUPS)[number]["key"];

type Prototype = {
  id: string; // "A".."I"
  path: string; // route path, e.g. "prototype/2024-ballot-question/audit/e-content-schemata"
  label: string;
  group: GroupKey;
  element: ReactNode;
};

// Every prototype A–I is routable by URL. Navigation is dev-only (see DevNav).
const PROTOTYPES: Prototype[] = [
  { id: "BQ", path: "ballotQuestions", label: "2026 Index", group: "ballot-questions", element: <BallotQuestions /> },
  { id: "D", path: "prototype/2024-ballot-question/audit/d-original", label: "Original", group: "2024-audit", element: <BallotQuestion /> },
  { id: "E", path: "prototype/2024-ballot-question/audit/e-content-schemata", label: "Content Schemata", group: "2024-audit", element: <ContentSchemata /> },
  { id: "F", path: "prototype/2024-ballot-question/audit/f-foragainst-1", label: "For & Against 1", group: "2024-audit", element: <ConceptF /> },
  { id: "G", path: "prototype/2024-ballot-question/audit/g-foragainst-2", label: "For & Against 2", group: "2024-audit", element: <ConceptG /> },
  {
    id: "H",
    path: "prototype/2024-ballot-question/audit/h-foragainst-hybrid",
    label: "For & Against Hybrid",
    group: "2024-audit",
    element: (
      <>
        <DisclaimerBar>
          All content in the For & Against Example, including campaign positions, research citations, and AI synthesis, was generated by AI for demonstration purposes only. This is not real ballot measure data.
        </DisclaimerBar>
        <ConceptH />
      </>
    ),
  },
  {
    id: "BQ2",
    path: "ballotQuestions/rent-control-alt",
    label: "Rent Control",
    group: "ballot-questions",
    element: <RentControlAlt />,
  },
];

const DEFAULT_PATH = "/prototype/2024-ballot-question/audit/e-content-schemata";

// Collapsible navigation panel flush against the bottom-right edge of the
// screen. Rendered only in development (see Layout) — Vite strips it from
// production builds.
function DevNav() {
  const { pathname } = useLocation();
  const [open, setOpen] = useState(true);

  if (!open) {
    return (
      <button
        onClick={() => setOpen(true)}
        className="fixed left-0 bottom-16 z-[60] shadow-lg"
        style={{ fontFamily: "Nunito", background: "#12266f", color: "#fff", borderTopRightRadius: 8, borderBottomRightRadius: 8, padding: "14px 8px", fontWeight: 800, fontSize: 11, letterSpacing: "0.1em", writingMode: "vertical-rl" }}
      >
        DEV NAV
      </button>
    );
  }

  return (
    <div
      className="fixed left-0 bottom-0 z-[60] shadow-lg"
      style={{ fontFamily: "Nunito", width: 260, background: "#fff", border: "1px solid #d1d1d1", borderLeft: "none", borderBottom: "none", borderTopRightRadius: 8, overflow: "hidden" }}
    >
      <div
        className="flex items-center justify-between"
        style={{ background: "#12266f", color: "#fff", padding: "6px 10px" }}
      >
        <span style={{ fontWeight: 800, fontSize: 11, letterSpacing: "0.1em" }}>DEV NAV</span>
        <button onClick={() => setOpen(false)} aria-label="Collapse dev nav" style={{ color: "#fff", fontSize: 16, lineHeight: 1, fontWeight: 700 }}>
          ×
        </button>
      </div>
      <div style={{ maxHeight: "60vh", overflowY: "auto", padding: 8 }}>
        {GROUPS.map((g) => (
          <div key={g.key} className="mb-2 last:mb-0">
            <div style={{ fontSize: 10, fontWeight: 800, color: "#888", textTransform: "uppercase", letterSpacing: "0.08em", padding: "4px 6px" }}>
              {g.title}
            </div>
            {PROTOTYPES.filter((p) => p.group === g.key).map((p) => {
              const active = `/${p.path}` === pathname;
              return (
                <Link
                  key={p.id}
                  to={`/${p.path}`}
                  className={active ? "block rounded" : "block rounded hover:bg-[#f0f0f0]"}
                  style={{
                    padding: "5px 8px",
                    fontSize: 12,
                    fontWeight: 700,
                    textDecoration: "none",
                    color: active ? "#fff" : "#334156",
                    background: active ? "#12266f" : undefined,
                  }}
                >
                  <span style={{ opacity: 0.55, marginRight: 6 }}>{p.id}</span>
                  {p.label}
                </Link>
              );
            })}
          </div>
        ))}
      </div>
    </div>
  );
}

// Persistent chrome. In production this is just the routed content; the dev nav
// only renders during `npm run dev`.
function Layout() {
  // Dev Nav is hidden by default (even in dev). Toggle it with ⌘/Ctrl+Shift+D;
  // the choice persists in localStorage. Keep adding new prototypes to the
  // PROTOTYPES registry regardless — they appear here whenever it's enabled.
  const [devNav, setDevNav] = useState(
    () =>
      typeof localStorage !== "undefined" &&
      localStorage.getItem("maple-devnav") === "1",
  );
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (
        (e.metaKey || e.ctrlKey) &&
        e.shiftKey &&
        (e.key === "D" || e.key === "d")
      ) {
        e.preventDefault();
        setDevNav((v) => {
          const next = !v;
          localStorage.setItem("maple-devnav", next ? "1" : "0");
          return next;
        });
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);
  return (
    <div className="min-h-screen bg-background">
      <Outlet />
      {import.meta.env.DEV && devNav && <DevNav />}
    </div>
  );
}

export default function App() {
  return (
    <Routes>
      <Route element={<Layout />}>
        <Route index element={<Navigate to={DEFAULT_PATH} replace />} />
        {PROTOTYPES.map((p) => (
          <Route key={p.id} path={p.path} element={p.element} />
        ))}
        {/* Unknown paths fall back to the default prototype */}
        <Route path="*" element={<Navigate to={DEFAULT_PATH} replace />} />
      </Route>
    </Routes>
  );
}
