import type { ReactNode } from "react";
import {
  Navigate,
  Outlet,
  Route,
  Routes,
  useLocation,
  useNavigate,
} from "react-router-dom";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./components/ui/select";

import ConceptOne from "./components/concept-one";
import ConceptTwo from "./components/concept-two";
import ConceptThree from "./components/concept-three";
import BallotQuestion from "./components/ballot-question";
import ContentSchemata from "./components/content-schemata";
import ConceptF from "./components/concept-f";
import ConceptG from "./components/concept-g";
import ConceptH from "./components/concept-h";
import ConceptRentControl from "./components/concept-rent-control";

// Sticky disclaimer shown below the concept switcher on certain prototypes;
// content scrolls under it.
function DisclaimerBar({ children }: { children: ReactNode }) {
  return (
    <div className="sticky top-[48px] z-40 h-[37px] bg-[#fef3c7] border-b border-[#f59e0b] px-[16px] flex items-center gap-[8px]">
      <span className="text-[16px]">⚠️</span>
      <p className="font-['Nunito'] font-bold text-[13px] text-[#92400e] leading-[1.4]">
        {children}
      </p>
    </div>
  );
}

type Prototype = {
  id: string; // "A".."I"
  path: string; // route segment, e.g. "prototype-e"
  label: string;
  sub?: string;
  desc?: string;
  visible: boolean; // whether it appears in the dropdown selector
  element: ReactNode;
};

// Every prototype A–I is routable by URL (/prototype-a … /prototype-i).
// Only those with `visible: true` appear in the dropdown selector.
const PROTOTYPES: Prototype[] = [
  { id: "A", path: "prototype/legislator-profile/a-compact", label: "Concept One", visible: false, element: <ConceptOne /> },
  { id: "B", path: "prototype/legislator-profile/b-standard", label: "Concept Two", visible: false, element: <ConceptTwo /> },
  { id: "C", path: "prototype/legislator-profile/c-full", label: "Concept Three", visible: false, element: <ConceptThree /> },
  { id: "D", path: "prototype/2024-ballot-question/audit/d-original", label: "Ballot Question", visible: false, element: <BallotQuestion /> },
  {
    id: "E",
    path: "prototype/2024-ballot-question/audit/e-content-schemata",
    label: "Content Schemata",
    sub: "Inventory View",
    desc: "Content inventory organized by tab — showing all content types and sources per section.",
    visible: true,
    element: <ContentSchemata />,
  },
  { id: "F", path: "prototype/2024-ballot-question/audit/f-foragainst-1", label: "Concept F", visible: false, element: <ConceptF /> },
  { id: "G", path: "prototype/2024-ballot-question/audit/g-foragainst-2", label: "Concept G", visible: false, element: <ConceptG /> },
  {
    id: "H",
    path: "prototype/2024-ballot-question/audit/h-foragainst-hybrid",
    label: "For & Against Example",
    sub: "Hybrid Approach",
    desc: "For & Against tab: Arguments synthesis, cross-cutting analysis, then research evidence.",
    visible: true,
    element: (
      <>
        <DisclaimerBar>
          All content in the For & Against Example, including campaign positions, research citations, and AI synthesis, was generated by AI for demonstration purposes only. This is not real ballot measure data.
        </DisclaimerBar>
        <ConceptH />
      </>
    ),
  },
  {
    id: "I",
    path: "prototype/2026-ballot-question/rent/i-ballotpedia-test",
    label: "Rent Control Example",
    sub: "Real Content Example",
    desc: "Rent control example",
    visible: true,
    element: (
      <>
        <DisclaimerBar>
          This initiative was removed from the November 2026 ballot by the Massachusetts Supreme Judicial Court on June 23, 2026. Content is sourced from Ballotpedia and Massachusetts official government sources. Displayed as if it were on the ballot for prototype purposes.
        </DisclaimerBar>
        <ConceptRentControl />
      </>
    ),
  },
];

const VISIBLE_PROTOTYPES = PROTOTYPES.filter((p) => p.visible);
const DEFAULT_PATH = "/prototype/2024-ballot-question/audit/e-content-schemata";

// Persistent chrome: the fixed concept switcher strip plus the routed content.
function Layout() {
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const current = PROTOTYPES.find((p) => `/${p.path}` === pathname);
  // Only reflect the dropdown selection when on a visible prototype.
  const selectValue = current?.visible ? current.path : undefined;

  return (
    <div className="min-h-screen bg-background">
      {/* Fixed concept switcher strip */}
      <div
        className="fixed top-0 left-0 right-0 z-50 flex items-center gap-0 border-b"
        style={{
          backgroundColor: "#fff",
          borderColor: "#d1d1d1",
          height: 48,
          paddingLeft: 16,
          paddingRight: 16,
        }}
      >
        <span
          className="mr-5 shrink-0"
          style={{ fontFamily: "Nunito", fontWeight: 700, fontSize: 12, color: "#888", textTransform: "uppercase", letterSpacing: "0.1em" }}
        >
          IA Concepts
        </span>

        {/* Prototype selector */}
        <Select value={selectValue} onValueChange={(path) => navigate(`/${path}`)}>
          <SelectTrigger
            className="w-[300px] h-8 shrink-0"
            style={{ fontFamily: "Nunito", fontWeight: 700, fontSize: 13, color: "#334156" }}
          >
            <SelectValue placeholder="Select a prototype…" />
          </SelectTrigger>
          <SelectContent>
            {VISIBLE_PROTOTYPES.map((p) => (
              <SelectItem key={p.id} value={p.path} style={{ fontFamily: "Nunito", fontWeight: 700, fontSize: 13 }}>
                {p.id} — {p.label}
                {p.sub ? <span style={{ fontWeight: 400, opacity: 0.75 }}> — {p.sub}</span> : null}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        {/* Description */}
        <div className="hidden lg:flex items-center ml-6 shrink-0">
          <span style={{ fontFamily: "Nunito", fontSize: 12, color: "#606060" }}>
            {current?.desc}
          </span>
        </div>
      </div>

      {/* Routed content — offset for the strip */}
      <div style={{ paddingTop: 48 }}>
        <Outlet />
      </div>
    </div>
  );
}

export default function App() {
  return (
    <Routes>
      <Route element={<Layout />}>
        <Route index element={<Navigate to={DEFAULT_PATH} replace />} />
        {PROTOTYPES.map((p) => (
          <Route key={p.id} path={p.path} element={p.element} />
        ))}
        {/* Unknown paths fall back to the default prototype */}
        <Route path="*" element={<Navigate to={DEFAULT_PATH} replace />} />
      </Route>
    </Routes>
  );
}
